# Generated by Django 5.2.8 on 2025-11-19 02:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('barbershops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='barbershop',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='barbershop_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='barbershopservice',
            name='barbershop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='barbershops.barbershop'),
        ),
        migrations.AddField(
            model_name='employee',
            name='barbershop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='barbershops.barbershop'),
        ),
        migrations.AddField(
            model_name='operation',
            name='barbershop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='barbershops.barbershop'),
        ),
        migrations.AddField(
            model_name='rating',
            name='barbershop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='barbershops.barbershop'),
        ),
        migrations.AddField(
            model_name='rating',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='operation',
            unique_together={('barbershop', 'weekDay')},
        ),
    ]
