# Generated by Django 5.2.8 on 2025-11-20 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershops', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Endereço', 'verbose_name_plural': 'Endereços'},
        ),
        migrations.AddField(
            model_name='barbershop',
            name='slug',
            field=models.SlugField(default='temp-slug', unique=True),
            preserve_default=False,
        ),
    ]
