# Generated by Django 5.2.8 on 2025-11-28 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershops', '0003_alter_address_options_barbershop_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='barbershop',
            name='telephone',
            field=models.CharField(default=123, max_length=20),
            preserve_default=False,
        ),
    ]
