# Generated by Django 5.2.8 on 2025-11-30 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershops', '0004_barbershop_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='barbershop',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='barbershop',
            name='ratings_count',
            field=models.IntegerField(default=0),
        ),
    ]
