# Generated by Django 5.2.8 on 2025-12-03 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershops', '0005_barbershop_rating_barbershop_ratings_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barbershop',
            name='imageUrl',
            field=models.ImageField(blank=True, null=True, upload_to='barbershops/'),
        ),
        migrations.AlterField(
            model_name='barbershopservice',
            name='imageUrl',
            field=models.ImageField(blank=True, null=True, upload_to='services/'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='urlProfilePhoto',
            field=models.ImageField(blank=True, null=True, upload_to='employees/'),
        ),
    ]
