# Generated by Django 5.2.8 on 2025-12-05 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershops', '0006_alter_barbershop_imageurl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='barbershopservice',
            name='duration_minutes',
            field=models.IntegerField(default=30, verbose_name='Duração (min)'),
        ),
    ]
