# Generated by Django 5.2.8 on 2025-11-30 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershops', '0005_barbershop_rating_barbershop_ratings_count'),
        ('bookings', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='barbershop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='barbershops.barbershop'),
            preserve_default=False,
        ),
    ]
