# Generated by Django 5.2.8 on 2025-11-30 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershops', '0005_barbershop_rating_barbershop_ratings_count'),
        ('bookings', '0003_booking_barbershop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='barbershops.employee'),
        ),
    ]
